version: '3.8'

services:
  api-gateway:
    build: ./http-api-gatway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gatway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - microservices

  users-microservice:
    build: ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - microservices

  payments-microservice:
    build: ./payments-microservice
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_URL=nats://nats:4222
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=test_user
      - DB_PASSWORD=testeuser123
      - DB_NAME=nestjs_db
    depends_on:
      - nats
      - mysql_db
    networks:
      - microservices

  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - microservices

  mysql_db:
    image: mysql:8.0
    ports:
      - "3307:3306"  # host:container
    environment:
      MYSQL_ROOT_PASSWORD: 17.03ikram
      MYSQL_DATABASE: nestjs_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: testeuser123
    networks:
      - microservices

networks:
  microservices:
